services:
  api:
    build: .
    container_name: digimon-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL:-}
      CODESPACE_FRONTEND_URL: ${CODESPACE_FRONTEND_URL:-}